logging:
  receivers:
    webapp-a6-github-receiver:
      type: files
      include_paths:
        - /var/log/webapplogs/*.log
      record_log_file_path: true
  processors:
    webapp-a6-github-processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
  service:
    pipelines:
      default_pipeline:
        receivers: [webapp-a6-github-receiver]
        processors: [webapp-a6-github-processor]