name: integration-tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Create .env file"
        run: |
          touch .env
          echo DB_HOST=localhost >> .env  # Assuming the service is accessed via localhost within the runner
          echo DB_NAME=${{ vars.DB_NAME }} >> .env
          echo DB_USER=${{ vars.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DIALECT=postgres >> .env  # Example of a non-sensitive data, hardcoded
          echo PORT=${{ vars.PORT }} >> .env

      - name: Install dependencies
        run: npm ci

      - name: Install PostgreSQL client (Optional)
        run: npm install pg

      - name: Run tests
        run: npm run test
        
