name: unittesting

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: "Create .env file"
        run: |
          touch .env
          echo DB_HOST=localhost >> .env  # Assuming the service is accessed via localhost within the runner
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DIALECT=postgres >> .env  # Example of a non-sensitive data, hardcoded

      - name: Install dependencies
        run: npm ci

      - name: Install PostgreSQL client (Optional)
        run: npm install pg

      - name: Run tests
        run: npm run test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
