name: unittesting

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    environment: ${{ vars.ENVIRONMENT }}
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ vars.DB_NAME }}
          POSTGRES_USER: ${{ vars.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - name: "Create .env file"
        run: |
          touch .env
          echo HOST=${{ vars.DB_HOST }} >> .env
          echo DBNAME=${{ vars.DB_NAME }} >> .env
          echo USERNAME=${{ vars.DB_USER }} >> .env
          echo PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DBDIALECT=${{ vars.DB_DIALECT }} >> .env
      - run: npm ci
      - run: npm install pg
      - run: npm run test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432